### ISSUE TITLE
Allow wrapping and collapsing function and method call parameters.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#13]
A neat feature would be to be able to collapse and wrap method or function calls, for example:

``` php
$this->test(1, 2, 3);

// "Wrap parameters over several lines"
$this->test(
    1,
    2,
    3
);
```

``` php
$this->test(
    1,
    2,
    3
);

// "Collapse parameters to a single line"
$this->test(1, 2, 3);
```

This is useful when working with PSR-2 or a soft line length boundary. Adding new arguments to an invocation can exceed the line length and removing existing arguments can make the wrapping over several lines unnecessary. 
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/394).
