### ISSUE TITLE
A self-assigned variable is not picked up as needing to be a parameter when extracting a method.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#17]
If you extract:

``` php
$test = $test2->foo();
```

... `$test2` will be added as parameter to the extracted method. However, if you extract:

``` php
$test = $test->foo();
```

... `$test` is not picked up.
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/395).
