### ISSUE TITLE
Feature: Constructor Injection Autocompletion

### ISSUE THREAD

**Issue by cabloo** [php-integrator/atom-refactoring#18]
[Original issue](https://github.com/Gert-dev/php-integrator-autocomplete-plus/issues/55) (copied below). I have recently been [made aware](https://github.com/Gert-dev/php-integrator-autocomplete-plus/issues/55#issuecomment-228614442) of the `Generate Constructor` feature of this package, which is on the right track for what I'm looking for, but not quite as easy.

I have yet to find an Atom package for this, and it may be out of the scope of this package (i.e. should be added to another `php-integrator` package), but I was really hoping for a package that would automate Service Injection as much as possible for me.

For those unfamiliar, almost every start of a class in my project looks something like this:

``` php
class TargetFinder
{
    /**
     * @var FormatService
     */
    protected $format;

    /**
     * @var RtgRouterRepository
     */
    protected $routers;

    /**
     * @var RtgInterfaceRepository
     */
    protected $targets;

    public function __construct(
        FormatService $format,
        RtgRouterRepository $routers,
        RtgInterfaceRepository $targets
    ) {
        $this->format = $format;
        $this->routers = $routers;
        $this->targets = $targets;
    }

    // Implementation...
}
```

Laravel detects and injects (resolves an instance of and passes as an argument) each of those variables required by the constructor. I find myself typing most of that out, which is quite inefficient. I have snippets for the doc blocks and usually use multi-copy-paste but that still is not quick enough for me.

I think ideal functionality for me would be a command I run that asks for the name of the variable and the class name (auto-completed), but another thing that could work is when typing in a function I could `ctrl-shift-click` (or similar) on a class variable that does not exist yet and it would request a class name to auto inject for it. For instance, if I were in the above class, and I decided I needed a Cache implementation, I could type

``` php
function find($id)
{
    return $this->cache->get('targets.'.$id, function () use ($id) {
        // resolve from database
    });
}
```

And since cache isn't a class variable I could trigger a special click on it that asks what class and adds it above, i.e. if I typed `Cache` it would `use` the right `Cache` and then add it to the constructor and add the protected variable with a doc block. Since this would only occur if `$this->cache` was not found as a variable, maybe it would be the same command as the `php-integrator-navigator` package (`ctrl-alt-click`), since navigator would essentially be saying "I don't know where this variable is, do you want to inject one?"

This is a Sublime command which seems to do something similar to what I'm trying to achieve above:

https://github.com/erichard/SublimePHPCompanion/blob/master/php_companion/commands/insert_php_constructor_property.py

**Comment by Gert-dev** [comment]
I've added another ticket that is closely related to this (#34) based on what I've observed from what PhpStorm does. What happens here is that if you have an existing constructor and you want a new parameter, you:
* Type out the parameter in the constructor parameter list (i.e. specify the type hint and name).
* Alt-enter the new parameter, select `Introduce field` (or similar).
* `$this->someNewParameter = $someNewParameter;` is added inside the constructor.
* $someNewParameter is introduced as property in the class itself if it doesn't exist yet.

This means you basically only have to type out the new parameter with its new type once in the constructor and the rest is automated with the command.

Also, as a side note. In a recent version the `Introduce property` command was already added, which allows you to alt-enter on an undefined property and automatically add it to the class. It's a little bit buggy (with regards to putting the property in the right place, which will improve in the next version) and still an additional step compared to the above process, but it might save you some time already until something better is implemented.

**Comment by cabloo** [comment]
@Gert-dev thanks, I'm currently mostly using the alt-enter intention for generating a constructor based on properties. The `Introduce property` command will help when I am editing an existing class and am adding dependencies.

I haven't tried it yet, but I just wanted to make sure that `Introduce property` works for any function (not just constructor)? I see no reason it shouldn't, and a few reasons it should.

**Comment by Gert-dev** [comment]
That's correct, `Introduce property` should work in any method, not just the constructor. The new `Introduce field` (or whatever it ends up being called) would then probably be specific to the constructor and use the same code `Introduce property` uses, with some additional steps.

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/396).
