### ISSUE TITLE
Bug: Method Extraction does not go all the way out of brackets

### ISSUE THREAD

**Issue by agleis** [php-integrator/atom-refactoring#19]
I've posted a gif of this issue below, but basically, in certain situations (especially in highly complex or nested functions), method extraction will 'paste' the method outside of the wrong set of brackets, such that it is still inside the original method. An example of this would be:

```
public function method() {
    if(8 == 8) {
        for($i = 0; $i < 10; $i++) {
            $i++;
            $i--;
        }
    }
}
```

Extracting the `$i++` and `$i--` lines would produce:

```
public function method() {
    if(8 == 8) {
        for($i = 0; $i < 10; $i++) {
            $this->test($i);
        }
    }
    /**
     * @param $i
     */
    public function test($i) {
        $i++;
        $i--;
    }
}
```

As you can see, the new function is still inside the original method brackets. It probably wouldn't happen with a function this small, but that's the idea. I have noticed this quite a few times when I've been working on more complex classes, and it is a bit annoying. See the gif below for a real example of this bug happening.

![extract-method-error](https://cloud.githubusercontent.com/assets/14354439/17114345/7c850150-527c-11e6-9a4f-f607ac28060c.gif)
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/411).
