### ISSUE TITLE
Support updating docblock @param tags based on modified parameters

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#24]
This should atetmpt to maintain existing descriptions and only update existing names. If the new parameter count is different from the old, adding entirely new ones as well as removing now-missing ones is fine.
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/393).
