### ISSUE TITLE
Only show intentions relevant to the current scope

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#25]
Currently things such as getter and setter generation also show inside methods. With the `ScopeChain` command from the base package (currently in a separate branch in need of rebasing) this can be fixed.
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/397).
