### ISSUE TITLE
Support creating new classlikes from the file browser

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#26]
Creating PHP files by entering the namespace manually becomes cumbersome quickly. We can automatically fill out the namespace based on the folder hierarchy, although where it starts depends on the project (i.e. it could be configured in `composer.json`).

We do want to avoid tying ourselves to Composer unless absolutely necessary, IIRC PhpStorm has a way to mark a project folder as namespace root via the file browser.
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/398).
