### ISSUE TITLE
Introduce property should try to guess the type of the new property

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#28]
To do this, the cursor can be moved to the end of the statement, followed by a call to `DeduceTypes` with the name of the property.

This possibly needs improvements to the base package first, as the type of properties is currently always deduced from the property itself (which doesn't yet exist in this case) and is not subject to local conditional type checks or assignments in the same way local variables are. See also [1].

[1] https://github.com/Gert-dev/php-integrator-base/issues/193
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/399).
