### ISSUE TITLE
Don't generate 'get' for getters for boolean values.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#3]
We should refrain from generating the `get` prefix for boolean properties:

``` php
public function getFoo(); // Normal property.
public function isActive(); // Instead of getIsActive.
public function hasSomething(); // Instead of getHasSomething.
public function wasSomewhere(); // Instead of getWasSomewhere.
```

We can do this for all boolean properties, instead of doing magic based on the name of the property, as we know their type. This behavior should be enabled by default, but togglable via the dialog; some users might still want the full name.
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/392).
