### ISSUE TITLE
Support introducing fields

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#34]
Whenever you add a new parameter to a constructor signature, you should be able to select `Introduce Field`, which will automatically add a `$this->newFieldName = $newFieldName` and afterwards execute an `Introduce Property` with the correct name _and_ type.

Of ocurse, `Introduce property` should only happen if the property does not already exist.

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/401).
