### ISSUE TITLE
Investigate automatically adding use statements in various commands

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#36]
Currently, when performing tasks such as overriding methods, use statements for those types are not automatically added. For these tasks, it makes sense that this happens automatically (and in the same transaction), as you will immediately end up with unknown class names after the task completes.

Candidates for this include:
- Override method
- Stub abstract method
- Stub interface method
- Generate constructor (could include properties from a parent class with types that aren't locally imported)
- Getter/setter generation (same)

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/403).
