### ISSUE TITLE
Don't suggest "Generate @inheritDoc" for methods when the parameter list differs

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-refactoring#38]
You can't inherit the entire documentation from a parent method if its parameter list is different, as the documentation doesn't apply.

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/404).
