### ISSUE TITLE
Refactoring Capabilities: Rename Variable, Method & Class

### ISSUE THREAD

**Issue by prolificrohit** [php-integrator/atom-refactoring#43]
It would be great if refactoring capabilities could be added to the plugin like renaming variables, methods and classes.

Renaming class name should also rename file name and it should be renamed at all the places where this class in used. Also moving files between directories should also rename namespaces and use statements at all places.

This is the only feature which i miss a lot in atom editor while using it for php. Refactoring is something which everyone needs from time to time and it would be wonderful feature if added in this plugin.

**Comment by VentyCZ** [comment]
I would also love this, especially the variable renaming option, that would be awesome!

To the second paragraph, not everyone uses the folder per namespace, file per class convention (not everytime/everywhere I mean), so I would say that there'd need to be some rules like, if the file has the same name as the class, rename would replace both (or just add an option to the rename dialog for the classes).

Moving files (and renaming, adding, removing? directories) is quite an advanced function I'd say in response to the simple change in name of the namespace - that I'd still have the user be responsible for... or at least make it optional.

**Comment by zestllankesh** [comment]
Even I feel that renaming variables/functions should be an integral part of code refactoring

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/412).
