### ISSUE TITLE
Not possible to generate getters / setters with message "Properties not found"

### ISSUE THREAD

**Issue by woozy** [php-integrator/atom-refactoring#50]
Everytime I try to use the generate methods it throws the message "Properties not found". 

I'm using PHP 7.1 and I have php-integrator-base and intentions package installed. 

Any tips on this?

**Comment by Gert-dev** [comment]
If I understood correctly: the window to select the properties pops up, but it shows a message that no properties could be found?

Properties are fetched via the core from the class that the cursor is in when opening the intention, so no properties showing up would indicate some kind of indexing problem.

**Comment by woozy** [comment]
@Gert-dev that's correct. It's a new project, I forgot to do the setup current project! It's working now. 

Thanks for the tip and sorry to bother! :)
