### ISSUE TITLE
Provide template and/or more customisation options

### ISSUE THREAD

**Issue by mdeboer** [php-integrator/atom-refactoring#57]
I'm absolutely in love with the getter/setter generation except that I always have to do a round of regex replace to get all docblocks how I want them.

For instance I want to have one space between parentheses and colon for return type declaration like `public function foo() : void`, except it doesn't. Also it adds `@return static` on setters instead of `@return MyClass` with a return type declaration, like I would want it to. It's a fine standard but I'm just picky 😆 

Anyway I've seen other (outdated) packages that allows you to set a getter and setter template. Even if it were only for the docblocks it would be amazing to have. Or if templates are not the way to go for some reason, I wouldn't mind having some settings to tweak the things I mentioned above.

**Comment by mdeboer** [comment]
Cheers, I'll look into that. Not familiar with PhpStorm really, made me feel going back to the dark ages when I worked with Eclipse.

If you're interested, this is one of the packages I was referring to that uses templates. It's not working too well as it's largely unmaintained but it might be of some use for inspiration: https://github.com/francodacosta/atom-php-getters-setters

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/410).
